version: '3.9'
services:

  redis:
    image: redis:7
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    
  worker:
    build: .
    command: celery -A app.workers.worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
      - ./resources:/code/resources
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - BACKEND_URL=http://backend:80
    depends_on:
      - redis