version: '3.9'
services:

  redis:
    image: redis:7
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
  
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "postgres"
      PGUSER: "postgres"
    ports:
      - 5433:5432
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 40s
      timeout: 20s
      retries: 5 

  backend:
    build: .
    ports:
      - 8004:80
    volumes:
      - ./app:/usr/src/app
      - ./resources:/code/resources
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_HOST_URL=postgres:5432
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
  
  worker:
    build: .
    command: celery -A app.workers.worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
      - ./resources:/code/resources
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - BACKEND_URL=http://backend:80
    depends_on:
      - backend
      - redis

  celery-broker-app:
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - BACKEND_URL=http://backend:80
    depends_on:
      - backend
      - redis
      - worker
